package middleware

import (
	"net/http"

	"github.com/arandu-io/framework/security"
)

// StatusCSRFExpired is the status returned when the token is missing, invalid or
// expired. 419 is the conventional status for it, kept on purpose: HTMX can be told to
// reload the page on 419, which is the only useful reaction to an expired token.
const StatusCSRFExpired = 419

// CSRFProtect validates the token on every state-changing method.
//
// THE TRAP THIS SOLVES: with HTMX the token does not arrive in a form field, it
// arrives in a header. The base template generated by the CLI carries
//
//	<body hx-headers='{"X-CSRF-Token": "{{ .CSRFToken }}"}'>
//
// and this middleware accepts both sources. Without that line every project
// starts out broken, which is why `aru doctor` checks for it.
//
// sessionIDFrom must return the id only for a valid session cookie -- pass
// SessionStore.IDFromRequest, which verifies the signature first.
func CSRFProtect(c *security.CSRF, sessionIDFrom func(*http.Request) string) func(http.Handler) http.Handler {
	safe := map[string]bool{
		http.MethodGet: true, http.MethodHead: true, http.MethodOptions: true, http.MethodTrace: true,
	}

	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if safe[r.Method] {
				next.ServeHTTP(w, r)
				return
			}

			token := r.Header.Get("X-CSRF-Token")
			if token == "" {
				token = r.PostFormValue("_csrf")
			}

			// A missing token and an expired one are different mistakes, and
			// they used to produce the same sentence. "Session expired" sends
			// the developer to look at session lifetimes, when the form simply
			// never carried the field -- which is the first thing that happens
			// to anybody wiring a form or an HTMX request by hand. Found by
			// audit.
			if token == "" {
				http.Error(w, "this request carried no CSRF token: add the hidden _csrf field to the form, or send it as the X-CSRF-Token header", StatusCSRFExpired)
				return
			}
			if err := c.Validate(sessionIDFrom(r), token); err != nil {
				http.Error(w, "this CSRF token is no longer valid: the session it belongs to expired or was replaced. Reload the page and submit again", StatusCSRFExpired)
				return
			}
			next.ServeHTTP(w, r)
		})
	}
}
