package unit

import (
	"crypto/rand"
	"encoding/base64"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/arandu-io/framework/config"
)

// inProject writes a .env in a temporary working directory, the way a generated
// project has one, and undoes what Load put in the process environment.
//
// The cleanup is not optional. Load fills the environment of the running
// process -- which is the point, since everything downstream reads os.Getenv --
// and in a test binary that environment outlives the test. A leftover
// DB_CONNECTION would decide the outcome of the next one.
func inProject(t *testing.T, content string) {
	t.Helper()

	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, ".env"), []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
	t.Chdir(dir)

	for _, raw := range strings.Split(content, "\n") {
		line := strings.TrimSpace(raw)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		name, _, ok := strings.Cut(strings.TrimPrefix(line, "export "), "=")
		if !ok {
			continue
		}
		name = strings.TrimSpace(name)
		t.Cleanup(func() { _ = os.Unsetenv(name) })
	}
}

// emptyProject makes an empty directory the working directory: no .env at all,
// which is what a container looks like.
func emptyProject(t *testing.T) {
	t.Helper()
	t.Chdir(t.TempDir())
}

// TestAMissingEnvFileIsNotAnError is the production case, and it is the one that
// must never regress: there is no file, the orchestrator set the variables, and
// a loader that insisted on a file would take the deployment down.
func TestAMissingEnvFileIsNotAnError(t *testing.T) {
	emptyProject(t)
	t.Setenv("APP_KEY", strings.Repeat("k", appKeyLen))
	t.Setenv("DATABASE_URL", "sqlite://database/database.sqlite")

	if _, err := config.Load(); err != nil {
		t.Fatalf("Load without a .env: %v", err)
	}
}

// TestTheEnvFileFillsWhatTheEnvironmentDoesNotDefine covers the shape of a real
// file: section comments, blank lines, and the `export ` prefix somebody pastes
// in from a shell script.
func TestTheEnvFileFillsWhatTheEnvironmentDoesNotDefine(t *testing.T) {
	inProject(t, `# --- config/app.go ---
APP_NAME=billing

# The key is generated by aru new.
APP_KEY=`+strings.Repeat("k", appKeyLen)+`

export HTTP_ADDR=:9000
DATABASE_URL=sqlite://database/database.sqlite
`)

	cfg, err := config.Load()
	if err != nil {
		t.Fatalf("Load: %v", err)
	}

	if cfg.AppName != "billing" {
		t.Errorf("AppName = %q, want billing", cfg.AppName)
	}
	if cfg.HTTPAddr != ":9000" {
		t.Errorf("HTTPAddr = %q, want :9000 -- the `export ` prefix must be ignored", cfg.HTTPAddr)
	}
	if len(cfg.AppKey) != appKeyLen {
		t.Errorf("AppKey is %d bytes, want %d", len(cfg.AppKey), appKeyLen)
	}
}

// TestQuotesAreOptionalAndStripped: both forms appear in every .env anyone has
// ever written, and a value that keeps its quotes fails much later -- as a
// token that does not verify or a path that does not exist.
func TestQuotesAreOptionalAndStripped(t *testing.T) {
	inProject(t, `APP_KEY="`+strings.Repeat("k", appKeyLen)+`"
DATABASE_URL=sqlite://database/database.sqlite
APP_NAME='the billing app'
HTTP_ADDR=":8081"
`)

	cfg, err := config.Load()
	if err != nil {
		t.Fatalf("Load: %v", err)
	}

	if cfg.AppName != "the billing app" {
		t.Errorf("AppName = %q, want the value without its single quotes", cfg.AppName)
	}
	if cfg.HTTPAddr != ":8081" {
		t.Errorf("HTTPAddr = %q, want the value without its double quotes", cfg.HTTPAddr)
	}
	if len(cfg.AppKey) != appKeyLen {
		t.Errorf("AppKey is %d bytes: the quotes were counted as key material", len(cfg.AppKey))
	}
}

// TestAValueMayContainEquals: a DSN, a base64 key with padding and a password
// all carry "=", and splitting on the last one -- or on every one -- truncates
// them silently.
func TestAValueMayContainEquals(t *testing.T) {
	const dsn = "postgres://u:p@host:5432/db?sslmode=require&application_name=billing"
	inProject(t, `APP_KEY=`+strings.Repeat("k", appKeyLen)+`
DATABASE_URL=`+dsn+`
`)

	cfg, err := config.Load()
	if err != nil {
		t.Fatalf("Load: %v", err)
	}

	if cfg.Database.URL != dsn {
		t.Fatalf("DATABASE_URL = %q, want %q", cfg.Database.URL, dsn)
	}
}

// TestTheEnvironmentWinsOverTheFile is the rule that keeps production intact.
//
// The orchestrator sets the real values. A .env that got copied into an image by
// accident must not be able to overrule them -- otherwise a stale file decides
// which database a deployment talks to.
func TestTheEnvironmentWinsOverTheFile(t *testing.T) {
	inProject(t, `APP_KEY=`+strings.Repeat("f", appKeyLen)+`
APP_NAME=from-the-file
DATABASE_URL=sqlite://from-the-file.sqlite
`)
	t.Setenv("APP_NAME", "from-the-environment")
	t.Setenv("DATABASE_URL", "sqlite://from-the-environment.sqlite")
	t.Setenv("APP_KEY", strings.Repeat("e", appKeyLen))

	cfg, err := config.Load()
	if err != nil {
		t.Fatalf("Load: %v", err)
	}

	if cfg.AppName != "from-the-environment" {
		t.Errorf("AppName = %q: the file overwrote a variable the environment had already defined", cfg.AppName)
	}
	if cfg.Database.Database != "from-the-environment.sqlite" {
		t.Errorf("DB_DATABASE = %q: a stale .env would choose the database", cfg.Database.Database)
	}
	if string(cfg.AppKey) != strings.Repeat("e", appKeyLen) {
		t.Error("APP_KEY came from the file: rotating the key through the environment would silently not happen")
	}
}

// TestAMalformedLineNamesTheFileAndTheLine: "the variable did not arrive" is a
// bug hunt, and the line number is what turns it into a one-second fix.
func TestAMalformedLineNamesTheFileAndTheLine(t *testing.T) {
	cases := map[string]struct {
		content string
		line    string
	}{
		"no equals sign": {
			content: "APP_KEY=" + strings.Repeat("k", appKeyLen) + "\nHTTP_ADDR :8080\n",
			line:    ".env:2",
		},
		"a name a shell would reject": {
			content: "APP_KEY=" + strings.Repeat("k", appKeyLen) + "\n\nAPP NAME=billing\n",
			line:    ".env:3",
		},
		"a quote that never closes": {
			content: "APP_KEY=\"" + strings.Repeat("k", appKeyLen) + "\n",
			line:    ".env:1",
		},
	}

	for name, c := range cases {
		t.Run(name, func(t *testing.T) {
			inProject(t, c.content)

			_, err := config.Load()
			if err == nil {
				t.Fatal("a malformed .env loaded without complaint")
			}
			if !strings.Contains(err.Error(), c.line) {
				t.Fatalf("the error does not name %s: %v", c.line, err)
			}
		})
	}
}

// TestThereIsNoInterpolation: ${OTHER} is where a .env format stops being a
// format and starts being a language, and a language has to be maintained
// forever. The value is what the file says it is.
func TestThereIsNoInterpolation(t *testing.T) {
	inProject(t, `APP_KEY=`+strings.Repeat("k", appKeyLen)+`
DATABASE_URL=sqlite://database/database.sqlite
APP_NAME=${OTHER}-suffix
`)
	t.Setenv("OTHER", "expanded")

	cfg, err := config.Load()
	if err != nil {
		t.Fatalf("Load: %v", err)
	}

	if cfg.AppName != "${OTHER}-suffix" {
		t.Fatalf("AppName = %q, want the literal value", cfg.AppName)
	}
}

// TestANewProjectCanRunMigrate is the defect, reproduced.
//
// `aru new crm` writes this file -- the skeleton's .env.example with a fresh
// base64 APP_KEY substituted in -- and prints "cd crm && aru migrate". Before
// the loader existed, nothing read it: migrate called config.Load, found an
// empty APP_KEY and died with "run `aru key:generate`", naming the command that
// had already been run.
//
// The last mile -- `aru new` cloning the skeleton and the binary dispatching
// "migrate" -- lives in the aru and arandu repositories. What migrate needs from
// here is a Config that loads and validates out of the file on disk, and that is
// what this asserts.
func TestANewProjectCanRunMigrate(t *testing.T) {
	key := make([]byte, appKeyLen)
	if _, err := rand.Read(key); err != nil {
		t.Fatal(err)
	}
	encoded := "base64:" + base64.StdEncoding.EncodeToString(key)

	inProject(t, `# Copy to .env and fill in. Never commit .env.

# --- config/app.go ---------------------------------------------------------
APP_NAME=crm
APP_ENV=dev
APP_URL=http://localhost:8080

# Generate with: aru key:generate
APP_KEY=`+encoded+`

HTTP_ADDR=:8080

# --- config/logging.go -----------------------------------------------------
LOG_LEVEL=info
LOG_FORMAT=

# --- config/database.go ----------------------------------------------------
DATABASE_URL=sqlite://database/database.sqlite

DATABASE_URL=

# --- config/session.go -----------------------------------------------------
SESSION_TTL=43200
CSRF_TTL=7200
`)

	cfg, err := config.Load()
	if err != nil {
		t.Fatalf("the first command of a new project failed: %v", err)
	}

	if string(cfg.AppKey) != string(key) {
		t.Fatal("the key migrate would sign sessions with is not the key aru new wrote")
	}
	if cfg.AppName != "crm" {
		t.Errorf("AppName = %q, want crm", cfg.AppName)
	}
	// What migrate does next: open the connection the file describes.
	if got := cfg.Database.SQLitePath(); got != "database/database.sqlite" {
		t.Errorf("SQLitePath = %q, want the path from the file", got)
	}
}
