// Package auth is the first first-party module and the canonical reference:
// every module the CLI generates has exactly this shape.
//
// Files of a module (vertical layout, not one directory per layer):
//
//	module.go       -> registration and routes
//	user.entity.go  -> the entity
//	user.policy.go  -> who may do what
//	user.repo.go    -> data access, requires a Grant
//	user.service.go -> business rules
//	user.request.go -> input types and Validate
package auth

import (
	"context"
	"net/http"

	fhttp "github.com/arandu-io/framework/http"
	"github.com/arandu-io/framework/http/middleware"
	"github.com/arandu-io/framework/kernel"
	"github.com/arandu-io/hesape/database/migrations"
)

// TenantResolver decides which tenant a request belongs to.
//
// It is only consulted on login, which is the one moment where there is no
// session to ask: everywhere else the tenant comes from the Grant, and therefore
// from the session. That asymmetry is the point -- a tenant taken from the
// request body or from a header after login would defeat the isolation the whole
// policy layer is built on.
type TenantResolver func(r *http.Request) string

// FixedTenant is the resolver for a single-tenant application: every login
// belongs to the same tenant.
//
// This is not a "single-tenant mode". It is the same code path with a constant
// where the resolver would be, which is why an application that starts single
// and grows into multi changes one line and no queries.
func FixedTenant(id string) TenantResolver {
	return func(*http.Request) string { return id }
}

// Module registers the authentication routes.
type Module struct {
	svc    *Service
	tenant TenantResolver
}

// New returns the module. The service and the tenant resolver are built by the
// caller, because the wiring is explicit: if you want to know where UserRepo
// comes from, it is written in the application's main.
//
// A nil resolver means the empty tenant, which is what a single-tenant
// application that never set one ends up with -- consistent, and still isolated,
// because every row is written with that same value.
func New(svc *Service, tenant TenantResolver) *Module {
	if tenant == nil {
		tenant = FixedTenant("")
	}
	return &Module{svc: svc, tenant: tenant}
}

// Compile-time proof that the module honors the kernel contracts it claims.
var (
	_ kernel.Module     = (*Module)(nil)
	_ kernel.Migratable = (*Module)(nil)
	_ kernel.Health     = (*Module)(nil)
)

// Name is the module identifier.
func (m *Module) Name() string { return "auth" }

// Routes registers the module's routes.
//
// The sign-in screen is guarded, and it is the one route here that needs to be:
// without the guest guard it renders for somebody who already has a session,
// which reads to them as having been signed out. There is nothing to guard on
// the two POSTs -- signing in again is harmless, and signing out without a
// session is a no-op that ends where it should.
func (m *Module) Routes(r *fhttp.Router) {
	g := r.Group("/auth")
	g.Get("/login", m.showLogin, middleware.RedirectIfAuthenticated(m.svc.session, "/"))
	g.Post("/login", m.doLogin)
	g.Post("/logout", m.doLogout)
}

// Health reports whether the module can reach its storage. It feeds
// /_arandu/health, so a database that went away turns into a failing probe
// rather than a stream of 500s.
func (m *Module) Health(ctx context.Context) error {
	return m.svc.repo.db.PingContext(ctx)
}

// Migrations declares the schema this module owns.
//
// They are returned in the order their names sort in, which is the order they
// apply in: the name carries the order, and nothing else decides it.
func (m *Module) Migrations() []kernel.Migration {
	return []kernel.Migration{createUsers{}, addNameAndVerificationToUsers{}}
}

// Both migrations are reversible, and the assertion is here rather than
// discovered at rollback: the Migrator tests for Down with a type assertion, so
// a Down with the wrong signature would leave a rollback that silently does
// nothing.
var (
	_ migrations.ReversibleMigration = createUsers{}
	_ migrations.ReversibleMigration = addNameAndVerificationToUsers{}
)

// createUsers is the users table and the index the listing reads it by.
type createUsers struct{ migrations.BaseMigration }

// GetName is the migration's identity, and it carries the order.
func (createUsers) GetName() string { return "20260729_0001_create_users" }

// Up creates the table and its index.
//
// Every type here spells the same in SQLite, PostgreSQL and MySQL, which is what
// lets one project develop on a file and deploy on Postgres without a second
// schema. The three things that would have broken that, and what replaced them:
//
//   - uuid columns are TEXT, and the id is generated by the application;
//   - roles are TEXT holding JSON, not jsonb and not text[];
//   - created_at has no database default, the value comes from Go.
//
// The email is stored lowercased by the repository, so a plain UNIQUE index is
// enough and no database-specific case-insensitive collation is needed.
func (createUsers) Up(ctx context.Context, conn migrations.Connection) error {
	if _, err := conn.Statement(ctx, `CREATE TABLE users (
    id          VARCHAR(255) PRIMARY KEY,
    -- Indexed, so VARCHAR rather than TEXT: see data.KeyText.
    tenant_id   VARCHAR(255) NOT NULL,
    email       VARCHAR(255) NOT NULL,
    password    TEXT NOT NULL,
    roles       TEXT NOT NULL,
    created_at  TIMESTAMP NOT NULL,
    UNIQUE (tenant_id, email)
)`, nil); err != nil {
		return err
	}

	_, err := conn.Statement(ctx,
		`CREATE INDEX users_tenant_created_idx ON users (tenant_id, created_at, id)`, nil)
	return err
}

// Down drops the table, which takes its index with it.
func (createUsers) Down(ctx context.Context, conn migrations.Connection) error {
	_, err := conn.Statement(ctx, `DROP TABLE users`, nil)
	return err
}

// addNameAndVerificationToUsers adds the display name and the verification
// timestamp.
//
// A second migration and not an edit to the first. The first one has run in
// every database this module has ever touched, and a migration is identified by
// its name: changing what an applied name means leaves the column missing
// everywhere it already ran, and nothing says so.
type addNameAndVerificationToUsers struct{ migrations.BaseMigration }

// GetName is the migration's identity, and it carries the order.
func (addNameAndVerificationToUsers) GetName() string {
	return "20260809_0002_add_name_and_verification_to_users"
}

// Up adds the two columns.
//
// Both are nullable: during a rollout the previous binary is still inserting
// rows without them, and a NOT NULL column with no default fails every one of
// those inserts.
//
// Two statements rather than one with two clauses: MySQL accepts
// `ADD COLUMN a, ADD COLUMN b`, SQLite does not.
func (addNameAndVerificationToUsers) Up(ctx context.Context, conn migrations.Connection) error {
	if _, err := conn.Statement(ctx, `ALTER TABLE users ADD COLUMN name VARCHAR(255)`, nil); err != nil {
		return err
	}
	_, err := conn.Statement(ctx, `ALTER TABLE users ADD COLUMN verified_at TIMESTAMP NULL`, nil)
	return err
}

// Down drops the two columns, one statement each for the reason Up gives.
func (addNameAndVerificationToUsers) Down(ctx context.Context, conn migrations.Connection) error {
	if _, err := conn.Statement(ctx, `ALTER TABLE users DROP COLUMN name`, nil); err != nil {
		return err
	}
	_, err := conn.Statement(ctx, `ALTER TABLE users DROP COLUMN verified_at`, nil)
	return err
}
