package auth

import (
	"context"
	"crypto/hmac"
	"crypto/sha256"
	"encoding/base64"
	"errors"
	"fmt"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/arandu-io/framework/data"
	"github.com/arandu-io/framework/events"
	"github.com/arandu-io/framework/observability"
	"github.com/arandu-io/framework/security"
)

// ErrInvalidCredentials is the single answer to a failed login. The reason lives
// in the log, never in the response: telling the client which half was wrong
// turns the endpoint into an account enumeration oracle.
var ErrInvalidCredentials = errors.New("auth: invalid credentials")

// TooManyAttemptsError is what a sign-in gets while the identity, and the
// address it arrived from, are locked out.
//
// It carries the time left rather than being a bare sentinel, because the screen
// has to be able to say something true. "Try again later" with no number is what
// makes somebody press the button four more times, and each press is an argon2
// hash this process did not need to compute.
//
// It says nothing about the account, and cannot: the lockout is decided before
// the users table is read, so the same answer arrives for an address that is
// registered and one that never was. Otherwise the enumeration oracle that
// ErrInvalidCredentials exists to close would reopen here, and it would be a
// better one -- a lockout that fires only for real accounts is a yes/no answer
// with no guessing left in it.
type TooManyAttemptsError struct {
	// RetryAfter is how much of the lockout is left.
	RetryAfter time.Duration
}

// Seconds is RetryAfter as a whole number of seconds, rounded up and never below
// one. It is what the Retry-After header and the sentence on the form both need,
// and rounding up is what keeps "try again in 0 seconds" off the screen.
func (e TooManyAttemptsError) Seconds() int {
	s := int((e.RetryAfter + time.Second - 1) / time.Second)
	if s < 1 {
		return 1
	}
	return s
}

// Error reports the lockout without naming the account it applies to.
func (e TooManyAttemptsError) Error() string {
	return "auth: too many sign-in attempts, try again in " + strconv.Itoa(e.Seconds()) + " seconds"
}

// The domain events this module publishes.
//
// They are the three moments another part of the system has to react to: a new
// account, an address that is now real, and a credential that changed. Anything
// else about a user is a row somebody can read.
//
// The names are past tense and in the vocabulary of the domain, which is what
// events.Event asks for: a consumer that had to diff two user rows to learn what
// happened would be a consumer coupled to this table.
const (
	// EventUserRegistered is somebody signing up. The account exists and the
	// address is not confirmed yet.
	EventUserRegistered = "auth.user.registered"
	// EventEmailVerified is the address being confirmed, and it is published
	// only by the click that confirmed it -- a second click on the same link
	// publishes nothing, or every welcome mail is sent twice.
	EventEmailVerified = "auth.email.verified"
	// EventPasswordReset is the password being replaced out of band.
	EventPasswordReset = "auth.password.reset"
)

// aggregateUser is what all three events happened to.
const aggregateUser = "user"

// UserEvent is the payload of every event this module publishes.
//
// One shape for the three, because they answer the same question -- which
// account, in which tenant, at which address -- and a consumer that already
// switches on the name should not also have to switch on the shape.
//
// The hash is not in it and must never be added: an outbox row is read by the
// relay, by whoever is looking at the dead letter queue, and by whatever the
// application publishes to. That is three places a credential would travel to
// for no reason.
type UserEvent struct {
	UserID string `json:"user_id"`
	Tenant string `json:"tenant_id"`
	Email  string `json:"email"`
	Name   string `json:"name,omitempty"`
}

// Service holds the business rules. It receives its dependencies through the
// constructor -- explicit wiring, generated by the CLI, no container.
type Service struct {
	repo    *UserRepo
	policy  UserPolicy
	session *security.SessionStore
	csrf    *security.CSRF
	// outbox is where the domain events go. It is built from the repository's
	// handle rather than passed in, because there is nothing to decide: an
	// application does not get to configure whether authentication emits its
	// events, only what publishes them (events.WithRelay).
	outbox *events.Outbox

	// throttle is what stands between a stolen password list and every account
	// in the table.
	//
	// Like the outbox, it is not a constructor parameter, and for a sharper
	// version of the same reason: a parameter is something a wiring file can
	// pass nil for, and a security control that can be wired off is one that is
	// wired off in the application that most needed it. It sits under
	// Authenticate rather than in a handler because the published sign-in screen
	// belongs to the project the moment the starter kit writes it -- a control
	// in a file the project may delete is a control that disappears.
	//
	// When the kv-backed implementation lands it replaces what this constructor
	// builds, here, for every application at once. Same interface, so it is an
	// adapter and not a mode (RULE 11).
	throttle security.SignInThrottle
}

// NewService wires the module.
func NewService(repo *UserRepo, session *security.SessionStore, csrf *security.CSRF) *Service {
	return &Service{
		repo:     repo,
		session:  session,
		csrf:     csrf,
		outbox:   events.NewOutbox(repo.db),
		throttle: security.NewMemoryThrottle(),
	}
}

// record stores one event next to the write that produced it.
//
// It must run inside data.Transaction, and a failure fails the whole operation
// rather than being logged and swallowed. That is the decision, and it is the
// opposite of the one a mail send gets: the outbox exists precisely so that the
// row and the event commit together. Swallowing this error restores the loss the
// events package refuses -- the account exists, nothing downstream ever hears of
// it, and there is no record anywhere that anything was missed. A rollback is
// visible, and the person retries and gets both.
func (s *Service) record(ctx context.Context, g security.Grant, name string, u User) error {
	return s.outbox.Store(ctx, g, []events.Event{{
		Name:        name,
		Aggregate:   aggregateUser,
		AggregateID: u.ID,
		Payload: UserEvent{
			UserID: u.ID, Tenant: u.TenantID, Email: u.Email, Name: u.Name,
		},
	}})
}

// Authenticate verifies the credentials and returns the user.
//
// # The identifier is the e-mail address, and there is no hook to change it
//
// This is the paragraph for whoever came looking for Laravel's username(). There
// is no equivalent, deliberately: an account is named by its address, in the
// form field, in LoginRequest.Email, in this parameter and in
// UserRepo.FindByEmail, and all four say so.
//
// What a hook would cost is not one method. The address is normalised on the way
// in and on the way out, and a plain UNIQUE (tenant_id, email) is what makes the
// lookup case-insensitive on every engine (see NormalizeEmail); the throttle key
// lower-cases and trims the identifier for that same reason, so a second kind of
// identifier with different rules is a second budget for the same account and
// twice the guesses. Registration, verification and the reset link are all built
// on proving control of an address -- a person who signed in by handle would
// have no proven address to reset through. And the hook itself is the second way
// to name an account, which is what RULE 9 refuses: two applications on this
// framework would disagree about what a login is.
//
// Signing in by handle is therefore an application-level feature -- resolve the
// handle to an address and call this -- and never a switch inside the framework.
//
// Note that there is no repository call without a Grant: the lookup by email
// uses SystemGrant, because at this point in the request there is no subject yet.
// That call is auditable, which is the point -- `aru doctor --strict` lists it.
//
// client is where the attempt came from, and it is half of the throttle key:
// pass middleware.KeyByIP(r), which reads the peer address and never a header
// the client can write. It is a parameter rather than something read from the
// context because a value that arrives implicitly is a value that arrives empty,
// and an empty one merges every attacker in the world into one counter -- which
// turns the lockout below into the way to lock a real account out.
//
// The throttle takes its unit here, before the users table is read, rather than
// after the password turns out to be wrong. Recording the failure afterwards
// leaves the length of an argon2 hash in which nothing has been written down,
// and a burst of simultaneous guesses all pass through it: measured, a budget of
// five answered eight requests fired at once, and would have answered as many as
// an attacker cared to open sockets for. The unit is given back below when the
// attempt never reached a credential, and forgotten entirely when it turns out
// to be the account's owner.
func (s *Service) Authenticate(ctx context.Context, tenant, email, plain, client string) (User, error) {
	log := observability.Log(ctx)

	retry, ok := s.throttle.Attempt(tenant, email, client)
	if !ok {
		// Before the lookup, so this answer cannot depend on whether the account
		// exists -- and so a locked-out flood costs no query and no argon2 hash.
		log.Warn("login blocked", "reason", "too_many_attempts", "retry_after", retry)
		return User{}, TooManyAttemptsError{RetryAfter: retry}
	}

	g := security.SystemGrant(ActionUserView, tenant)
	u, err := s.repo.FindByEmail(ctx, g, email)
	if err != nil {
		if !errors.Is(err, ErrUserNotFound) {
			// An outage is not a failed attempt. Counting it was the shape of
			// the bug this branch exists to prevent: a database that answers
			// every lookup with an error would spend every account's budget in
			// one minute and lock the whole tenant out of a system whose only
			// problem was that it was already broken.
			//
			// Refund and not Clear, because this branch is reachable by anyone
			// who hangs up mid-request: cancelling the context is an error here
			// too, and if that wiped the count then four guesses and one
			// abandoned request would be an unlimited number of guesses.
			s.throttle.Refund(tenant, email, client)
			log.Error("login failed", "reason", "lookup", "error", err)
			return User{}, err
		}
		// Same message and same time cost for a missing user and a wrong
		// password: otherwise the response time tells an attacker which emails
		// exist.
		_ = security.VerifyPassword(plain, timingHash())
		log.Warn("login failed", "reason", "unknown_user")
		return User{}, ErrInvalidCredentials
	}

	if err := security.VerifyPassword(plain, u.Password); err != nil {
		log.Warn("login failed", "reason", "wrong_password", "user", u)
		return User{}, ErrInvalidCredentials
	}

	// Cleared on the way in, not on the way out: whatever the rehash below does,
	// the password was right, and somebody who finally remembers it on the fifth
	// try must not be locked out by the four that came before.
	s.throttle.Clear(tenant, email, client)

	if security.NeedsRehash(u.Password) {
		if hash, err := security.HashPassword(plain); err == nil {
			u.Password = hash
			// SetPassword and not Update, for the reason SetPassword exists: the
			// row was read before the password was verified, and a full-row write
			// puts that snapshot back. A sign-in overlapping an administrator
			// granting a role would take the role away again -- on the strength
			// of nothing but the account's hashing parameters being out of date.
			//
			// The rehash is opportunistic: a failure must not fail the login,
			// because the credentials are already proven correct.
			if err := s.repo.SetPassword(ctx, security.SystemGrant(ActionUserUpdate, tenant), u.ID, hash); err != nil {
				log.Warn("password rehash failed", "user", u, "error", err)
			}
		}
	}

	log.Info("login succeeded", "user", u)
	return u, nil
}

// SubjectOf builds the session subject for a user. It is the only place that
// decides what goes into the session, which is what keeps roles out of reach of
// the request body.
func SubjectOf(u User) security.Subject {
	return security.Subject{
		ID: u.ID, Tenant: u.TenantID, Roles: u.Roles,
		// Carried into the session, so a policy can ask without a query. It is
		// as old as the session, and that fails in the safe direction: an
		// account starts unverified, so a stale session is more restrictive
		// than the truth and never less.
		Verified: u.Verified(),
	}
}

// CreateUser shows the full path: validate, Authorize, Grant, Repository.
func (s *Service) CreateUser(ctx context.Context, actor security.Subject, in CreateUserRequest) (User, error) {
	if errs := in.Validate(); errs.Any() {
		return User{}, errs
	}

	candidate := User{TenantID: actor.Tenant, Email: in.Email, Roles: in.Roles}

	g, err := security.Authorize(ctx, s.policy, actor, ActionUserCreate, candidate)
	if err != nil {
		return User{}, err
	}

	hash, err := security.HashPassword(in.Password)
	if err != nil {
		return User{}, fmt.Errorf("auth: hashing password: %w", err)
	}
	candidate.Password = hash

	created, err := s.repo.Create(ctx, g, candidate)
	if err != nil {
		return User{}, err
	}
	// Guarded: created is a struct value, and boxing it into `any` allocates at
	// the call site even though the method is a no-op on a nil Collector. See
	// Collector.RecordEvent.
	if col := observability.FromContext(ctx); col != nil {
		col.RecordEvent("auth.user.created", created)
	}
	return created, nil
}

// Register creates a user from a registration form.
//
// It is CreateUser with a guest in place of the actor, and nothing else. The
// tenant comes from the resolver rather than from the form -- a tenant a
// registration form could name is a registration form that joins any customer --
// and the roles are not read from the input at all: RegisterRequest has none,
// and the policy refuses a candidate that has any.
//
// The returned user is unverified. Sending the link is the caller's, because who
// the mail is from and what the link points at are the application's business
// and not this module's.
func (s *Service) Register(ctx context.Context, tenant string, in RegisterRequest) (User, error) {
	if errs := in.Validate(); errs.Any() {
		return User{}, errs
	}

	candidate := User{TenantID: tenant, Name: strings.TrimSpace(in.Name), Email: in.Email}

	// A declared guest, not an empty subject. Authorize refuses the empty one
	// before it reaches the policy, and rightly -- it is almost always a session
	// that failed to load. This one is anonymous on purpose and says so.
	g, err := security.Authorize(ctx, s.policy, security.Guest(tenant), ActionUserCreate, candidate)
	if err != nil {
		return User{}, err
	}

	hash, err := security.HashPassword(in.Password)
	if err != nil {
		return User{}, fmt.Errorf("auth: hashing password: %w", err)
	}
	candidate.Password = hash

	var created User
	if err := data.Transaction(ctx, s.repo.db, func(ctx context.Context) error {
		var err error
		if created, err = s.repo.Create(ctx, g, candidate); err != nil {
			return err
		}
		return s.record(ctx, g, EventUserRegistered, created)
	}); err != nil {
		return User{}, err
	}
	// The Collector call stays next to the outbox one, and they are not the same
	// thing: this is the ring buffer behind /_arandu/debug, nil outside
	// development and read by nobody but a person looking at a request. The line
	// above is the event another part of the system reacts to. Removing this one
	// would take the registration off the timeline of the request that caused it.
	//
	// Guarded: created is a struct value, and boxing it into `any` allocates at
	// the call site even though the method is a no-op on a nil Collector.
	if col := observability.FromContext(ctx); col != nil {
		col.RecordEvent(EventUserRegistered, created)
	}
	return created, nil
}

// ErrVerificationAddressChanged is a link that no longer belongs to the account
// it names: the address was replaced after the mail went out, or the payload is
// not one this application minted.
//
// It is one error and not two because a handler has one answer for both -- the
// link is not valid -- and because a payload carrying no address cannot match the
// stored one, which is the same refusal for the same reason.
var ErrVerificationAddressChanged = errors.New("auth: the verification link was issued for a different address")

// VerificationPayload is what a verification link carries: the account, and the
// address the link was mailed to.
//
// The address is in it because a link carrying only an id confirms whatever
// address the account has at the moment it is clicked, not the one somebody
// proved control of. Change the address after the mail is out and the old link
// still stamps the new one as verified, which is verification proving nothing.
// It was latent here only because no method changed an address yet, and whoever
// writes that method has no reason to open this file. Laravel binds the same two
// things, by hashing the address into the signed route.
//
// The id is written with its length in front of it, for the reason
// security.Signer writes the purpose that way: without it an id of "a" with an
// address of "b|c" and an id of "a|b" with an address of "c" are the same byte
// string, and a link minted for one account verifies another.
func VerificationPayload(u User) string {
	return strconv.Itoa(len(u.ID)) + ":" + u.ID + "|" + NormalizeEmail(u.Email)
}

// decodeVerificationPayload reads back what VerificationPayload wrote.
//
// The length decides where the id ends, so nothing in the address can move the
// boundary. A payload that does not parse is refused rather than guessed at.
func decodeVerificationPayload(payload string) (id, address string, ok bool) {
	prefix, rest, found := strings.Cut(payload, ":")
	if !found {
		return "", "", false
	}
	n, err := strconv.Atoi(prefix)
	if err != nil || n < 0 || n >= len(rest) || rest[n] != '|' {
		return "", "", false
	}
	return rest[:n], rest[n+1:], true
}

// MarkVerified records that the address was confirmed, and reports whether this
// call is what confirmed it.
//
// The boolean is what lets a handler tell "welcome, you are in" from "you
// already did this" -- the second one happens every time somebody clicks the
// link in a second e-mail client, and answering it with an error reads as the
// link being broken.
//
// A verification link proves control of the address it was sent to, and nothing
// else. So this takes the payload of the signed token and reads the row itself:
// nothing here is trusted to arrive from the request. The address in the payload
// is compared with the stored one, which is what binds the link to what it
// proved -- see VerificationPayload and ErrVerificationAddressChanged.
//
// The comparison is a plain one rather than a constant-time one: the address is
// not a secret from whoever is holding a link that was mailed to it, and the
// signature was already checked in constant time before this was called.
//
// The flip itself is UserRepo.Confirm, which changes the column only while it is
// still null. The check above cannot stand in for it: a link is opened by the
// person and prefetched by whatever scans their mail within the same second, and
// two reads that both saw an unverified row both used to write, and both used to
// store the event -- which is the welcome mail sent twice by a consumer behaving
// correctly. The boolean now comes from the database rather than from a read
// that had already gone stale.
func (s *Service) MarkVerified(ctx context.Context, tenant, payload string) (User, bool, error) {
	id, address, ok := decodeVerificationPayload(payload)
	if !ok {
		return User{}, false, fmt.Errorf("%w: the link carries no address", ErrVerificationAddressChanged)
	}

	view := security.SystemGrant(ActionUserView, tenant)
	u, err := s.repo.Find(ctx, view, id)
	if err != nil {
		return User{}, false, err
	}
	// Before the already-verified answer, not after: a link for an address the
	// account no longer has must be refused whatever state the account is in.
	if NormalizeEmail(address) != NormalizeEmail(u.Email) {
		return User{}, false, ErrVerificationAddressChanged
	}
	if u.Verified() {
		return u, false, nil
	}

	at := time.Now().UTC()
	var first bool
	if err := data.Transaction(ctx, s.repo.db, func(ctx context.Context) error {
		update := security.SystemGrant(ActionUserUpdate, tenant)
		var err error
		if first, err = s.repo.Confirm(ctx, update, id, at); err != nil {
			return err
		}
		if !first {
			// Somebody else stamped the column between the read above and this
			// statement. Nothing happened here, so nothing is stored: the event
			// belongs to the call that changed the row.
			return nil
		}
		u.VerifiedAt = at
		return s.record(ctx, update, EventEmailVerified, u)
	}); err != nil {
		return User{}, false, err
	}
	if !first {
		// Read again rather than reporting the snapshot: the winning call wrote
		// the timestamp, and a caller handed a User whose Verified() is false
		// right after a successful confirmation would be handed something untrue.
		u, err = s.repo.Find(ctx, view, id)
		return u, false, err
	}
	observability.Log(ctx).Info("email verified", "user", u)
	return u, true, nil
}

// FindForVerification reads a user by id, for the handler that has just checked
// a signed link and needs to know who it is about.
//
// It exists so that the handler does not reach the repository, and so that the
// SystemGrant is here, in the module that owns the table, where `aru doctor`
// already expects to find them.
func (s *Service) FindForVerification(ctx context.Context, tenant, userID string) (User, error) {
	return s.repo.Find(ctx, security.SystemGrant(ActionUserView, tenant), userID)
}

// Lookup returns a user by address, for a caller with no subject to authorize.
//
// It is what a seeder uses to find an account it did not create in the same run.
// The alternative is a SELECT on the users table from outside this module, and
// then that table has two owners -- which is how a schema change breaks code
// nobody thought was reading it.
//
// Never call it to decide whether an address is registered in a response. That
// is an account enumeration oracle, and every screen in this framework that
// could have been one answers the same thing either way.
func (s *Service) Lookup(ctx context.Context, tenant, email string) (User, error) {
	return s.repo.FindByEmail(ctx, security.SystemGrant(ActionUserView, tenant), email)
}

// Names resolves user ids to display names, for a screen that shows who wrote
// something.
//
// One query for the whole list. A comment thread that looked each author up
// separately would be an N+1 on the page most likely to have twenty rows on it.
//
// A failure is the caller's to decide about: a thread is worth rendering with
// ids in it, and not worth failing over.
func (s *Service) Names(ctx context.Context, tenant string, ids []string) (map[string]string, error) {
	return s.repo.NamesByID(ctx, security.SystemGrant(ActionUserView, tenant), ids)
}

// ErrResetLinkSpent is a password reset link that no longer names a password
// this application would change.
//
// One error for five refusals -- the payload does not parse, the typed address
// is not the one it was sent to, the account is gone, its address moved, the
// password already changed -- because the screen has one honest answer for all
// of them ("ask for another one"), and because five distinct answers would be
// five facts about somebody's account handed to whoever is holding a link they
// should not have.
var ErrResetLinkSpent = errors.New("auth: the password reset link is no longer valid")

// ResetPayload is what a password reset link carries: the tenant, the account,
// the address it was mailed to, and a fingerprint of the password that account
// had when the link was minted.
//
// Nothing is written when the mail goes out. That is the whole design (ADR
// 0032): no table, no cleanup job, no decision about what a click means once the
// row is gone -- and the second replica behind a load balancer accepts a link
// the first one issued, which an in-memory store of tokens cannot.
//
// # What makes it single use
//
// The fingerprint. Replacing the password replaces the hash, so every link ever
// minted against the old one stops verifying at the same instant -- the one that
// was just used, and any earlier ones still sitting in the inbox. A table would
// have had to delete the used row, remember to delete the siblings, and sweep
// what nobody ever clicked; this expires itself, and it expires the whole set.
//
// # Why the tenant is in it
//
// The link is consumed with no session, so there is no Grant to read the tenant
// from. Resolving it from the host at that moment is what RULE 14 forbids, and
// concretely: a link minted for one customer, posted at another customer's host,
// changed the password of whichever account had that address there. Read from
// the payload the tenant is not request data -- it is a value this application
// signed, which is the provenance a session cookie has.
//
// # Why the fields carry their length
//
// Every field is written with its byte length in front of it, for the reason
// security.Signer writes the purpose that way. With a plain separator, a tenant
// of "a" with an id of "b|c" and a tenant of "a|b" with an id of "c" are the
// same byte string, and a link minted for one account resets another.
func ResetPayload(u User) string {
	return field(u.TenantID) + field(u.ID) + field(NormalizeEmail(u.Email)) +
		field(passwordFingerprint(u.Password))
}

// field writes one value of a payload with its byte length in front of it, so
// that no value can move a boundary. See ResetPayload.
//
// VerificationPayload writes its two fields its own way and stays that way: the
// format is what every link already in an inbox was signed with, and changing it
// would refuse all of them at once for a tidiness nobody asked for.
func field(v string) string { return strconv.Itoa(len(v)) + ":" + v }

// nextField reads back what field wrote, returning the value and what is left.
//
// The length decides where the value ends, so nothing inside a value is read as
// a delimiter. A prefix that does not parse, or one that reaches past the end,
// is refused rather than guessed at.
func nextField(s string) (value, rest string, ok bool) {
	prefix, after, found := strings.Cut(s, ":")
	if !found {
		return "", "", false
	}
	n, err := strconv.Atoi(prefix)
	if err != nil || n < 0 || n > len(after) {
		return "", "", false
	}
	return after[:n], after[n:], true
}

// decodeResetPayload reads back what ResetPayload wrote.
func decodeResetPayload(payload string) (tenant, id, address, fingerprint string, ok bool) {
	rest := payload
	for _, out := range []*string{&tenant, &id, &address, &fingerprint} {
		if *out, rest, ok = nextField(rest); !ok {
			return "", "", "", "", false
		}
	}
	// Nothing may follow the four. Trailing bytes are a payload this application
	// did not write, and a parser that ignores what it does not understand is a
	// parser that accepts two spellings of one token.
	return tenant, id, address, fingerprint, rest == ""
}

// ResetAddress is the address a reset payload was minted for, or the empty
// string when the payload is not one this application wrote.
//
// It exists so the screen behind the link can fill in the e-mail field it asks
// for. That field was Required and never filled, so the one thing the person had
// to type on a form reached from their own inbox was the address the link had
// just been sent to.
//
// It is not authorization and proves nothing on its own: read it only from a
// payload that has already come out of security.Signer.Verify.
func ResetAddress(payload string) string {
	_, _, address, _, ok := decodeResetPayload(payload)
	if !ok {
		return ""
	}
	return address
}

// passwordFingerprint is the part of a reset payload that expires it.
//
// SHA-256 of the stored hash, truncated to 128 bits: far more than enough that
// no password anybody can choose produces the same fingerprint, and short enough
// that the link still fits on one line -- a link a mail client wrapped is a link
// that arrives broken, which this flow has already been bitten by.
//
// It is not the hash and it is not a secret: it is a one-way function of a value
// that is itself a one-way function of the password. A link read out of an inbox
// tells its reader nothing except whether the password has changed since.
func passwordFingerprint(hash string) string {
	sum := sha256.Sum256([]byte(hash))
	return base64.RawURLEncoding.EncodeToString(sum[:16])
}

// resetIdentity is what the reset budget is counted against.
//
// Keyed apart from the sign-in budget, and that is the point rather than an
// oversight: the person who has just got their password wrong five times is
// exactly the person who then clicks "forgot my password", and a shared counter
// would refuse them the recovery at the one moment they want it. What the two
// still share is the per-address budget inside the throttle, so one client
// cannot ask for more than that in a minute whichever form it posts to.
func resetIdentity(email string) string { return "reset:" + NormalizeEmail(email) }

// FindForReset returns the account a password reset link would be minted for,
// after taking one unit of the throttle's budget.
//
// The caller must answer identically whether this returns a user or
// ErrUserNotFound. A "send me a link" form that says "no such account" is an
// account enumeration oracle with a nicer name, and it is a better one than a
// sign-in form: one request, one bit, no password to guess.
//
// It is throttled here rather than in the screen for the reason Authenticate is:
// the published screen belongs to the project the moment the starter kit writes
// it, and a control in a file the project may delete is a control that
// disappears. Unthrottled, this endpoint is a way to send mail from this
// application's domain, to an address chosen by whoever found the URL, as often
// as they ask -- which is a sending reputation, not a form.
//
// client is where the request came from: pass middleware.KeyByIP(r), which reads
// the peer address and never a header the caller can write.
func (s *Service) FindForReset(ctx context.Context, tenant, email, client string) (User, error) {
	identity := resetIdentity(email)

	retry, ok := s.throttle.Attempt(tenant, identity, client)
	if !ok {
		// Before the lookup, like Authenticate's, so the answer cannot depend on
		// whether the address is registered.
		observability.Log(ctx).Warn("password reset blocked", "reason", "too_many_attempts", "retry_after", retry)
		return User{}, TooManyAttemptsError{RetryAfter: retry}
	}

	u, err := s.repo.FindByEmail(ctx, security.SystemGrant(ActionUserView, tenant), email)
	if err != nil {
		if !errors.Is(err, ErrUserNotFound) {
			// An outage is not an attempt. The same branch Authenticate has, for
			// the same reason: a database that answers every lookup with an error
			// would otherwise spend every account's budget in one minute.
			s.throttle.Refund(tenant, identity, client)
		}
		return User{}, err
	}

	// Deliberately no Clear. Naming an address that exists proves nothing about
	// it, and forgetting the count on a hit would make this the way out of the
	// lockout: post one known address whenever the budget runs low.
	return u, nil
}

// ResetPassword replaces the password of the account a reset payload names.
//
// The payload must already have come through security.Signer.Verify -- this
// checks what a signature cannot, which is whether the link is still the current
// one. See ResetPayload for why that is a fingerprint and not a row.
//
// address is what the person typed on the form, and it is compared with the one
// the link was minted for. It changes no outcome an attacker cares about, since
// the token is the credential; what it does is stop the form's Required e-mail
// field from being decoration. It was: the screen asked for an address, threw it
// away, and reset whichever account the token named.
//
// There is no tenant parameter. The tenant is in the payload, signed, exactly so
// that this call cannot be made to depend on the host the link was opened at.
func (s *Service) ResetPassword(ctx context.Context, payload, address, plain string) (User, error) {
	tenant, id, signedFor, fingerprint, ok := decodeResetPayload(payload)
	if !ok {
		return User{}, fmt.Errorf("%w: the payload is not one this application wrote", ErrResetLinkSpent)
	}
	if NormalizeEmail(address) != signedFor {
		return User{}, fmt.Errorf("%w: it was sent to a different address", ErrResetLinkSpent)
	}

	u, err := s.repo.Find(ctx, security.SystemGrant(ActionUserView, tenant), id)
	if err != nil {
		if errors.Is(err, ErrUserNotFound) {
			return User{}, fmt.Errorf("%w: the account it names is gone", ErrResetLinkSpent)
		}
		return User{}, err
	}
	// The address is compared against the stored one as well as against the typed
	// one, which is what binds the link to what it proved: control of the address
	// it was sent to. Change the address after the mail is out and the old link
	// stops working, rather than resetting the account at its new one.
	if NormalizeEmail(u.Email) != signedFor {
		return User{}, fmt.Errorf("%w: the address on the account changed after it was sent", ErrResetLinkSpent)
	}
	// hmac.Equal rather than ==, for consistency with every other comparison in
	// this framework that decides whether a token is accepted. The fingerprint is
	// not secret from whoever holds the link, so this buys nothing here -- and a
	// comparison that is constant-time only where somebody remembered is the one
	// that gets it wrong in the next file.
	if !hmac.Equal([]byte(passwordFingerprint(u.Password)), []byte(fingerprint)) {
		return User{}, fmt.Errorf("%w: the password changed after it was sent", ErrResetLinkSpent)
	}

	// Through SetPassword, like every other caller: one place hashes, one place
	// publishes EventPasswordReset. The extra lookup it does is one query on an
	// operation that has just spent a hundred times that on argon2.
	return s.SetPassword(ctx, u.TenantID, u.Email, plain)
}

// errNoSubjectToConfirm is ConfirmPassword refusing to check a password for
// nobody.
//
// An empty subject is a session that failed to load, not a wrong password, and
// the two have different answers: the sign-in screen, and "that is not the right
// password". Returning ErrInvalidCredentials here would tell somebody whose
// session had expired that they had typed their own password wrong.
var errNoSubjectToConfirm = errors.New("auth: confirming a password needs a subject with an id and a tenant")

// confirmIdentity is what the password-confirmation budget is counted against.
//
// The subject and not an address: whoever reaches this screen is already holding
// a session, and a session names a subject. It is kept apart from the sign-in
// budget so that guessing here cannot lock the account's owner out of the
// sign-in form, while the throttle's per-address budget still caps what one
// client gets in a minute across both.
func confirmIdentity(subjectID string) string { return "confirm:" + subjectID }

// ConfirmPassword re-verifies the password of a subject that is already signed
// in, for a screen that asks for it again before something that matters.
//
// It is not Authenticate. That one is the sign-in path: it takes an address,
// decides a tenant and hands back a user to open a session for. Widening it to
// also accept a subject would give one function two meanings and two failure
// modes, and the caller would pick between them with a nil (RULE 9). This one
// takes the subject the session already carries and answers a yes or no.
//
// It is throttled, and that is not optional: without it a screen behind
// RequireAuth is a password oracle for anybody holding a stolen session cookie
// -- unlimited guesses at the password of the account they have already taken,
// which is the password they will try on the next site.
//
// client is where the request came from: pass middleware.KeyByIP(r).
func (s *Service) ConfirmPassword(ctx context.Context, sub security.Subject, plain, client string) error {
	if sub.ID == "" || sub.Tenant == "" {
		return errNoSubjectToConfirm
	}

	identity := confirmIdentity(sub.ID)
	retry, ok := s.throttle.Attempt(sub.Tenant, identity, client)
	if !ok {
		observability.Log(ctx).Warn("password confirmation blocked", "reason", "too_many_attempts", "retry_after", retry)
		return TooManyAttemptsError{RetryAfter: retry}
	}

	u, err := s.repo.Find(ctx, security.SystemGrant(ActionUserView, sub.Tenant), sub.ID)
	if err != nil {
		if !errors.Is(err, ErrUserNotFound) {
			s.throttle.Refund(sub.Tenant, identity, client)
			return err
		}
		// A session naming an account that is not there any more. It is not a
		// wrong password, but it is not something to let through either, and the
		// attempt stays counted: a deleted id is not a free budget.
		return ErrInvalidCredentials
	}

	if err := security.VerifyPassword(plain, u.Password); err != nil {
		observability.Log(ctx).Warn("password confirmation failed", "user", u)
		return ErrInvalidCredentials
	}

	s.throttle.Clear(sub.Tenant, identity, client)
	return nil
}

// SetPassword replaces the password of an existing account, and publishes
// EventPasswordReset.
//
// It is the only method that replaces a password, and every caller goes through
// it: the published reset screen after it has consumed the signed link, the
// operator command for when nobody can reach that link -- the mail is not
// configured yet, the domain is not verified yet, the account is the first
// administrator and there is nobody to ask -- and a seeder. A second method for
// the screen would be a second place the hash is computed and a second place the
// event is published from, and one of the two would eventually stop publishing
// it (RULE 9).
//
// It proves nothing itself, and that is deliberate rather than missing. Who is
// allowed to do this is the caller's: the screen proves control of the address
// with a signed link before it calls, the command is a person at a terminal.
// Rules about the password -- a minimum length, a history -- are the
// application's for the same reason, and the published screen enforces its own.
// So do not reach this from anything a request can address without that proof in
// front of it.
//
// The hash is computed here, so no caller can be handed the chance to store a
// plain password by writing the field directly. It is computed before the
// transaction opens, because argon2 is a tenth of a second and holding a row
// lock for it is a tenth of a second every other writer of that row waits.
//
// # It writes one column
//
// This used to read the row, set the field, and write the whole row back with
// UserRepo.Update -- with the read outside the transaction. Anything that
// changed in between was reverted from a stale snapshot: a role granted while
// somebody was resetting their password disappeared again, and a verification
// clicked in the same minute was undone. Nothing failed and nothing was logged.
// UserRepo.SetPassword writes the one column, which is what MarkVerified was
// given in UserRepo.Confirm and for the same reason.
//
// The row is read back inside the transaction rather than reported from the
// snapshot, so what is returned and what is published describe the account as it
// is at commit. That matters most for the event: EventPasswordReset is what a
// "your password was changed" notice is sent from, and a payload carrying the
// address the account had a minute ago sends that notice to an address that no
// longer belongs to it.
func (s *Service) SetPassword(ctx context.Context, tenant, email, plain string) (User, error) {
	view := security.SystemGrant(ActionUserView, tenant)
	u, err := s.repo.FindByEmail(ctx, view, email)
	if err != nil {
		return User{}, err
	}

	hash, err := security.HashPassword(plain)
	if err != nil {
		return User{}, fmt.Errorf("auth: hashing password: %w", err)
	}

	var updated User
	if err := data.Transaction(ctx, s.repo.db, func(ctx context.Context) error {
		update := security.SystemGrant(ActionUserUpdate, tenant)
		if err := s.repo.SetPassword(ctx, update, u.ID, hash); err != nil {
			return err
		}
		var err error
		if updated, err = s.repo.Find(ctx, view, u.ID); err != nil {
			return err
		}
		return s.record(ctx, update, EventPasswordReset, updated)
	}); err != nil {
		return User{}, err
	}
	// Logged because it is an out-of-band credential change: the one event where
	// "who did this and when" is asked afterwards and there is no request to
	// answer with. The log is for a person reading it later; the event above is
	// for whatever has to act now -- sign the other sessions out, tell the
	// account owner, raise the flag on a fraud review.
	//
	// The message says what happened and not who did it, which it cannot know.
	// It used to say "from the command line", and the published reset screen is a
	// caller: every ordinary person recovering their password wrote a line into
	// the log that read as an operator changing somebody's credentials by hand --
	// which is exactly the line somebody greps for during an incident, and it was
	// never true. Which caller it was is in the context: a request has an id on
	// every line it emits and a command has none.
	observability.Log(ctx).Warn("password replaced", "user", updated)
	return updated, nil
}

// EnsureAdmin creates the first administrator of a tenant when it has none.
//
// It is deliberately NOT called at boot: seeding that happens by itself is how a
// known password ends up in production. Call it from a one-off command, with
// credentials that come from the environment.
func (s *Service) EnsureAdmin(ctx context.Context, tenant, email, plain string) (User, error) {
	g := security.SystemGrant(ActionUserView, tenant)
	if existing, err := s.repo.FindByEmail(ctx, g, email); err == nil {
		return existing, nil
	} else if !errors.Is(err, ErrUserNotFound) {
		return User{}, err
	}

	hash, err := security.HashPassword(plain)
	if err != nil {
		return User{}, fmt.Errorf("auth: hashing password: %w", err)
	}
	return s.repo.Create(ctx,
		security.SystemGrant(ActionUserCreate, tenant),
		User{TenantID: tenant, Email: email, Password: hash, Roles: []string{"admin"}})
}

// EnsureUser is EnsureAdmin for any account, and it is what a seeder calls.
//
// Same circle, same break: a seeder has no request behind it and therefore no
// subject, so there is no policy to ask. It is in the module that owns the table
// rather than in each application's seeders, so `aru doctor` has one call site to
// account for instead of one per project.
//
// verified writes the timestamp. A seeded reader who cannot comment because
// nobody clicked a link in a mailbox that does not exist is a demo that does not
// demonstrate anything -- and the flag is explicit here, so a seeder that wants
// the unverified case gets it by asking.
//
// It is idempotent: an existing address is returned untouched, including its
// password. A seeder that reset the password of an existing account would be a
// seeder that locked somebody out on the second run.
func (s *Service) EnsureUser(ctx context.Context, tenant, name, email, plain string, roles []string, verified bool) (User, error) {
	g := security.SystemGrant(ActionUserView, tenant)
	if existing, err := s.repo.FindByEmail(ctx, g, email); err == nil {
		return existing, nil
	} else if !errors.Is(err, ErrUserNotFound) {
		return User{}, err
	}

	hash, err := security.HashPassword(plain)
	if err != nil {
		return User{}, fmt.Errorf("auth: hashing password: %w", err)
	}

	u := User{TenantID: tenant, Name: name, Email: email, Password: hash, Roles: roles}
	if verified {
		u.VerifiedAt = time.Now().UTC()
	}
	return s.repo.Create(ctx, security.SystemGrant(ActionUserCreate, tenant), u)
}

// timingHash returns a throwaway hash used to equalize the response time of the
// unknown-user path. It is computed once, on first use, with the same parameters
// as production -- computing it at package init would make every binary that
// imports this module pay for argon2 at startup.
var timingHash = sync.OnceValue(func() string {
	h, _ := security.HashPassword("arandu-timing-equalization-hash")
	return h
})
