package auth

import (
	"context"
	"errors"
	"fmt"
	"sync"

	"github.com/arandu-io/framework/observability"
	"github.com/arandu-io/framework/security"
)

// ErrInvalidCredentials is the single answer to a failed login. The reason lives
// in the log, never in the response: telling the client which half was wrong
// turns the endpoint into an account enumeration oracle.
var ErrInvalidCredentials = errors.New("auth: invalid credentials")

// Service holds the business rules. It receives its dependencies through the
// constructor -- explicit wiring, generated by the CLI, no container.
type Service struct {
	repo    *UserRepo
	policy  UserPolicy
	session *security.SessionStore
	csrf    *security.CSRF
}

// NewService wires the module.
func NewService(repo *UserRepo, session *security.SessionStore, csrf *security.CSRF) *Service {
	return &Service{repo: repo, session: session, csrf: csrf}
}

// Authenticate verifies the credentials and returns the user.
//
// Note that there is no repository call without a Grant: the lookup by email
// uses SystemGrant, because at this point in the request there is no subject yet.
// That call is auditable, which is the point -- `aru doctor --strict` lists it.
func (s *Service) Authenticate(ctx context.Context, tenant, email, plain string) (User, error) {
	log := observability.Log(ctx)

	g := security.SystemGrant(ActionUserView, tenant)
	u, err := s.repo.FindByEmail(ctx, g, email)
	if err != nil {
		// Same message and same time cost for a missing user and a wrong
		// password: otherwise the response time tells an attacker which emails
		// exist.
		_ = security.VerifyPassword(plain, timingHash())
		log.Warn("login failed", "reason", "unknown_user")
		return User{}, ErrInvalidCredentials
	}

	if err := security.VerifyPassword(plain, u.Password); err != nil {
		log.Warn("login failed", "reason", "wrong_password", "user", u)
		return User{}, ErrInvalidCredentials
	}

	if security.NeedsRehash(u.Password) {
		if hash, err := security.HashPassword(plain); err == nil {
			u.Password = hash
			// The rehash is opportunistic: a failure must not fail the login,
			// because the credentials are already proven correct.
			if _, err := s.repo.Update(ctx, security.SystemGrant(ActionUserUpdate, tenant), u); err != nil {
				log.Warn("password rehash failed", "user", u, "error", err)
			}
		}
	}

	log.Info("login succeeded", "user", u)
	return u, nil
}

// SubjectOf builds the session subject for a user. It is the only place that
// decides what goes into the session, which is what keeps roles out of reach of
// the request body.
func SubjectOf(u User) security.Subject {
	return security.Subject{ID: u.ID, Tenant: u.TenantID, Roles: u.Roles}
}

// CreateUser shows the full path: validate, Authorize, Grant, Repository.
func (s *Service) CreateUser(ctx context.Context, actor security.Subject, in CreateUserRequest) (User, error) {
	if errs := in.Validate(); errs.Any() {
		return User{}, errs
	}

	candidate := User{TenantID: actor.Tenant, Email: in.Email, Roles: in.Roles}

	g, err := security.Authorize(ctx, s.policy, actor, ActionUserCreate, candidate)
	if err != nil {
		return User{}, err
	}

	hash, err := security.HashPassword(in.Password)
	if err != nil {
		return User{}, fmt.Errorf("auth: hashing password: %w", err)
	}
	candidate.Password = hash

	created, err := s.repo.Create(ctx, g, candidate)
	if err != nil {
		return User{}, err
	}
	// Guarded: created is a struct value, and boxing it into `any` allocates at
	// the call site even though the method is a no-op on a nil Collector. See
	// Collector.RecordEvent.
	if col := observability.FromContext(ctx); col != nil {
		col.RecordEvent("auth.user.created", created)
	}
	return created, nil
}

// EnsureAdmin creates the first administrator of a tenant when it has none.
//
// It is deliberately NOT called at boot: seeding that happens by itself is how a
// known password ends up in production. Call it from a one-off command, with
// credentials that come from the environment.
func (s *Service) EnsureAdmin(ctx context.Context, tenant, email, plain string) (User, error) {
	g := security.SystemGrant(ActionUserView, tenant)
	if existing, err := s.repo.FindByEmail(ctx, g, email); err == nil {
		return existing, nil
	} else if !errors.Is(err, ErrUserNotFound) {
		return User{}, err
	}

	hash, err := security.HashPassword(plain)
	if err != nil {
		return User{}, fmt.Errorf("auth: hashing password: %w", err)
	}
	return s.repo.Create(ctx,
		security.SystemGrant(ActionUserCreate, tenant),
		User{TenantID: tenant, Email: email, Password: hash, Roles: []string{"admin"}})
}

// timingHash returns a throwaway hash used to equalize the response time of the
// unknown-user path. It is computed once, on first use, with the same parameters
// as production -- computing it at package init would make every binary that
// imports this module pay for argon2 at startup.
var timingHash = sync.OnceValue(func() string {
	h, _ := security.HashPassword("arandu-timing-equalization-hash")
	return h
})
