// Package data defines the data access contract.
//
// There is no ORM. Queries are plain parameterized SQL -- generated by sqlc from
// .sql files once phase 2 lands -- which makes SQL injection impossible and the
// query plan predictable. What this package adds on top is:
//
//  1. a security.Grant required by every operation (the mandatory path);
//  2. tenant scoping taken from the Grant, never from a parameter;
//  3. automatic instrumentation into the Collector.
package data

import (
	"context"
	"database/sql"
	"time"

	"github.com/arandu-io/framework/observability"
	"github.com/arandu-io/framework/security"
)

// Repository is the contract every module repository implements.
//
// Look at the signature: security.Grant is mandatory and comes before the id.
// Because a Grant cannot be constructed outside the security package, there is
// no path from a handler to the database that skips a Policy.
type Repository[T any, ID comparable] interface {
	Find(ctx context.Context, g security.Grant, id ID) (T, error)
	List(ctx context.Context, g security.Grant, q Query) ([]T, error)
	Create(ctx context.Context, g security.Grant, entity T) (T, error)
	Update(ctx context.Context, g security.Grant, entity T) (T, error)
	Delete(ctx context.Context, g security.Grant, id ID) error
}

// Query is pagination and ordering with an allowlist. The sort field is NEVER
// interpolated directly: the repository validates it against a permitted set,
// or ordering becomes injection through another door.
type Query struct {
	Limit  int
	Cursor string
	Sort   string
	Filter map[string]any
}

// DB wraps *sql.DB to instrument the Collector. Repositories use this type
// rather than *sql.DB, which is what makes every query show up on the debug page
// with the file and line that issued it.
//
// It holds no driver import: the driver is chosen by the application, so the
// core keeps its two dependencies.
type DB struct {
	inner *sql.DB
}

// Wrap returns an instrumented handle over an open *sql.DB.
func Wrap(db *sql.DB) *DB { return &DB{inner: db} }

// Unwrap returns the underlying handle, for the rare case that needs a driver
// specific feature. Prefer the wrapper: what goes through Unwrap does not show
// up on the debug page.
func (d *DB) Unwrap() *sql.DB { return d.inner }

// PingContext verifies the connection. It feeds module health checks.
func (d *DB) PingContext(ctx context.Context) error { return d.inner.PingContext(ctx) }

// QueryContext runs a query and records it.
func (d *DB) QueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error) {
	start := time.Now()
	rows, err := d.inner.QueryContext(ctx, query, args...)
	observability.FromContext(ctx).RecordQuery(query, args, time.Since(start), -1, err)
	return rows, err
}

// ExecContext runs a statement and records it, with the affected row count.
func (d *DB) ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error) {
	start := time.Now()
	res, err := d.inner.ExecContext(ctx, query, args...)
	rows := -1
	if err == nil && res != nil {
		if n, e := res.RowsAffected(); e == nil {
			rows = int(n)
		}
	}
	observability.FromContext(ctx).RecordQuery(query, args, time.Since(start), rows, err)
	return res, err
}

// QueryRowContext runs a single-row query and records it.
//
// The duration measured here covers issuing the query only: database/sql defers
// the actual work to Row.Scan, so a slow row shows up on the timeline as scan
// time rather than query time.
func (d *DB) QueryRowContext(ctx context.Context, query string, args ...any) *sql.Row {
	start := time.Now()
	row := d.inner.QueryRowContext(ctx, query, args...)
	observability.FromContext(ctx).RecordQuery(query, args, time.Since(start), 1, nil)
	return row
}

// BeginTx starts a transaction on the underlying handle.
//
// Statements inside the transaction are not recorded by the Collector yet: that
// needs a wrapper over *sql.Tx, which arrives with the generated repositories in
// phase 2.
func (d *DB) BeginTx(ctx context.Context, opts *sql.TxOptions) (*sql.Tx, error) {
	return d.inner.BeginTx(ctx, opts)
}

// Tenant returns the tenant from the Grant. Every multi-tenant statement must
// take this value, never a tenant that came in with the request.
func Tenant(g security.Grant) string { return g.Subject().Tenant }
